In [233]:
import re

In [234]:
class Uzel:
    
    """
    класс узел в дереве. 
    Хранит 4 параметра: 
    1) id, который одновременно является указателем порядка в предложении
    2) parent -- id узла родителя
    3) 
    4) 
    """
    
    def __init__(self, id_number, word, parent, pos):
        self.id_number = id_number
        self.word = word
        self.parent = parent
        self.pos = pos

In [235]:
def parse_file (path_to_file):
    with open (path_to_file, 'r') as conllfile:
        sentence_id = '0'
        for line in conllfile:
            if line.startswith('# sent_id'):
                sentence_id = re.search ('sent_id = (\d+)', line).group(1)
            elif re.match ('\d', line):
                add_line_with_node_to_all_sent (line, sentence_id)

In [236]:
def add_line_with_node_to_all_sent (some_line, sentence_id):
        new_node = parse_node (some_line)
        if sentence_id in all_sentences:
            all_sentences[sentence_id].append(new_node)
        else:
            all_sentences[sentence_id] = [new_node]

In [237]:
def parse_node (some_line):
    node_features = some_line.split('\t')
    id_number = node_features[0]
    word = node_features[1]
    pos = node_features[3]
    parent = node_features[6]
    new_node = Uzel (id_number,word, parent, pos)
    return (new_node)

In [238]:
all_sentences = {} # сюда сложим все предложения в виде списка объектов нашего класса Uzel

In [239]:
PATH_TO_FILE = 'boris.conllu.txt'

In [240]:
parse_file (PATH_TO_FILE) # заполним all_sentences

In [241]:
len(all_sentences)

132

In [242]:
noun_phrases = [] # сюда сложим именные группы

In [243]:
def get_noun_phrases (sentences_dict):
    for sentence_index in sentences_dict:
        sentence_nodes = sentences_dict [sentence_index]
        for node in sentence_nodes:
            if node.pos == 'NOUN':
                this_node_and_descendents = []
                this_node_and_descendents.append (node)
                noun_phrase = get_descendents (node, sentence_nodes, this_node_and_descendents)
                noun_phrases.append (noun_phrase)

In [244]:
def get_descendents (this_node, sentence_nodes, this_node_and_descendents):
    for some_node in sentence_nodes:
        if some_node.parent == this_node.id_number:
            this_node_and_descendents.append  (some_node)
            get_descendents (some_node, sentence_nodes, this_node_and_descendents)
    return this_node_and_descendents

In [245]:
def print_ordered_noun_phrases (some_noun_phrases_list):
    for phrase in some_noun_phrases_list:
        # отсортируем по id_number, который у нас кодирует исходный порядок слов:
        sorted_phrase = sorted(phrase, key = lambda item: item.id_number)
        sorted_phrase_text = []

        for node in sorted_phrase:
        #sorted_phrase_text.append (node.word)
            sorted_phrase_text.append (node.id_number)

        print (' '.join (sorted_phrase_text))

In [246]:
get_noun_phrases(all_sentences)

In [247]:
len(noun_phrases)

322

In [248]:
print_ordered_noun_phrases(noun_phrases)

1 2
2
6 7 8
10 5 6 7 8 9
1 2
10 11 12 13 14 9
4 5 6 7
8
10 11 12 13 14 15 16 17 18 19 20
11 12 13 14 15 16 17 18 19 20
10 11 12 13 14 15 16 17 18 19 20 3 4 7 8 9
4
5 6
10 11 12 13 14 15 16 17 18 19 20 7 8 9
13 14 15 16 17 18 19 20
15 16 17 18 19 20
1 10 11 12 2 3 4 5 6 7 8 9
10 11 12 3 4 5 6 7 8 9
6 7
7
11
1 2 3
6 7 8
1 2
11 12 13 14
13 14
4 5
1 2 3 4
3 4 5 6 7 8
5 6 7 8
6 7 8
1 2 3
1 2 3 4 5 6 7
2
4 5
8
11
5 6 7
6 7
1 2
8 9
1
6 7 8 9
1 2
8
13 14 15 16 17
15 16 17
17
3
3 4 5 6 7
10 8 9
13 14 15 16 17 18 19
14 15 16 17 18 19
16 17 18
1 2 3
3
5 6
1 2
1
1 2 3 4 5 6
4 5
1 2 3 4 5 6 7 8
5 6 7
5 6 7 8
2 3
5 6
1 2
5
3 4
12
1 2
3 4 5
10 9
3 4 5 6
4 5 6
6 7 8
7 8
10 11
20 21 22 23 24 25 26
5 6
1 2
10 11 6 7 8 9
10 11 9
1 2
10 11 12 13 14 15 16 2 3 4 5 6 7 8 9
10 11 12 13 14 15 16 4 5 6 7 8 9
10 11 12 13 14 15 16
1 2
10
1 2 3 4 5 6 7 8
3 4 5 6 7 8
5 6 7 8
10 11
10 5 6 7 8 9
2
10 11 12 13 7 8 9
8 9
10 11 12
1 2
10 8 9
11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
16 17 18
21 22
20 21 22 23 24
1 2
1 2 3 4 5
3 4
2 3
4
2 3 4 5 6 7 8
7 8
1 2
4 5
10 11 12 13
12 13
1 2
10 11 8 9
12 13 14 15 16
14 15
10 11
1
3 4 5
5
1
3 4 5 6
5 6
1
4
10 9
13 14 15 16 17
20 21
12 13 14 15
13 14 15
15
1
4
6 7 8
16 17 18 19 20 21 22 23
21 22 23
2 3
5 6
8 9
1
6 7
4 5 6 7
12 13
14 15 16 17 18
16 17 18
18
23 24
1
10 11 8 9
13 14 15
10 11 4 5 6 7 8 9
14 15 16 17 18 19 20 21 22 23 24 25
15 16 17
19 20
23 24
2
10 11 12 13 14 15 16 8 9
9
11 12
13 14 15 16
10 8 9
12 13 14 15 16 17 18 19 20
14
5 6 7 8 9
6 7 8 9
10 11 12
1 2 3 4
6 7 8
2 3
5 6
7 8
10 11 12 13 14 15 16 3 4 5 6 7 8 9
7 8 9
11 12 13 14 15
13 14 15
1 2
2 3
5
1
6
10 9
1
10 11 12 13 14 15 16 17 18
14 15 16 17
16 17
1 2 3
7 8
1 10 11 2 3 4 5 6 7 8 9
1
7 8
1
6 7 8
13 14 15 16 17 18
4 5
16
3
8
12 13
4
10 11 12 13 3 4 5 6 7 8 9
10 11 12 13 6 7 8 9
10 11 12 8 9
14
15
10 11 12 13 14 15 4 5 6 7 8 9
6 7 8 9
9
10 11 12 13 14 15
12 13 14
17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37
22
24 25 26 27
30 31 32
33 34 35 36
35 36
5 6 7 8
10 11
16 17
4 5 6
7
11
1
10 11 12
1 2
10 11 12 13 14 15 16 5 6 7 8 9
13 14 15
1 2 3 4
5 6 7
1 2 3 4
10 11 12 13 14 15 16 17 18 6 7 8 9
11 12
14 15 16 17
1 2 3
10 5 6 7 8 9
10 7 8 9
13 14 15
1 2 3 4
2 3
10 11 6 7 8 9
10 11 8 9
2 3
10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 4 5 6 7 8 9
10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 8 9
10 11 12 13 14
17 18 19 20
15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
24 25 26 27 28 29
26
15 16
17 18 19 20 21
20 21
24 25
26
31 32
33 34
1 2 3 4
10 5 6 7 8 9
10 7 8 9
13 14 15 16
14 15 16
17 18 19 20 21 22
10 11 12 13 14 15 16 5 6 7 8 9
10 9
11 12 13 14 15
13 14 15
6 7 8
1 10 2 3 4 5 6 7 8 9
9
1 2 3
4 5 6
6
5
7 8 9
10 11 12 13 6 7 8 9
10 11 12 13 5 6 7 8 9
10 9
12 13
1 2 3
10 9
1
5 6 7
1 2
2 3
3
1 2
10 8 9
10
3 4 5 6 7 8 9
6 7 8 9
1
10 8 9
12 13 14
4 5 6
10 11
1 2 3 4
1 2 3
4
5 6 7 8 9
8 9
17 18 19 20
1 2 3 4 5 6 7 8 9
1
1 2
2
7 8
2
1 2 3 4
1 10 11 12 13 14 15 16 2 3 4 5 6 7 8 9
10 11
10 11 12 13 14 15 16 8 9
2 3 4 5 6
4 5 6 7 8
1
11 12
10 11
12 13 14
14
1
3 4

In [249]:
import pandas as pd

### avericheva

In [280]:
with open('avericheva.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    b = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        b.append(file[q])


df = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : b
                  })
df.head(2)

   id id токенов ИГ
0   0             1
1   1         2 3 4

### natan

In [281]:
with open('natan.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    c = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        c.append(file[q])


df1 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : c
                  })
df1.head(2)

   id id токенов ИГ
0   0             1
1   1       3 4 5 6

### sariban

In [283]:
with open('sariban.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    d = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        d.append(file[q])


df2 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : d
                  })
df2.head(2)

   id id токенов ИГ
0   0           1 2
1   1           5 6

### shabalina

In [284]:
with open('shabalina.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    e = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        e.append(file[q])

df3 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : e
                  })
df3.head(2)

   id id токенов ИГ
0   0     5 6 7 8 9
1   1           8 9

### shavrova

In [285]:
with open('shavrova.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    fel = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        fel.append(file[q])


df4 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : fel
                  })
df4.head(2)

   id    id токенов ИГ
0   0  2 3 4 5 6 7 8 9
1   1                2

### ilia

In [286]:
with open('ilia.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    g = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        g.append(file[q])


df5 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : g
                  })

### voronina

In [287]:
with open('voronina.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    h = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        h.append(file[q])


df6 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : h
                  })

### pit

In [288]:
with open('pit.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    l = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        l.append(file[q])


df7 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : l
                  })

### alfred

In [289]:
with open('alfred.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    m = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        m.append(file[q])


df8 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : m
                  })

### clavdia

In [290]:
with open('clavdia.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    n = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        n.append(file[q])


df9 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : n
                  })

### abrenev

In [291]:
with open('abrenev.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    p = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        p.append(file[q])


df10 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : p
                  })

### fedor abramov

In [292]:
with open('fedor_abramov.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    r = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        r.append(file[q])


df11 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : r
                  })

### marius petipa

In [293]:
with open('marius_petipa.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    st = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        st.append(file[q])


df12 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : st
                  })

### petr saburov

In [294]:
with open('petr_saburov.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    w = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        w.append(file[q])


df13 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : w
                  })

### andrey palashnikov

In [295]:
with open('andrey_palashnikov.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    rt = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        rt.append(file[q])


df14 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : rt
                  })

### nicolay durnovo

In [296]:
with open('nicolay_durnovo.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    gt = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        gt.append(file[q])


df15 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : gt
                  })

### boris

In [297]:
with open('boris.txt') as f:
    text = f.read()
    file = text.splitlines()
    q = -1  # счетчик для итерации по срезам 
    fin = []  # список с id токенов ИГ
    ids = list(range(0, len(file)))  # id
    
    for line in file:
        q = q + 1
        fin.append(file[q])


df16 = pd.DataFrame({
    'id': ids,
    'id токенов ИГ' : fin
                  })

## Запись в БД

In [311]:
#import sqlite3
#conn = sqlite3.connect('name_phrases.db')
import sqlite3
conn = sqlite3.connect('NounPhrases.db')

df.to_sql( 'автор1' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор1
         ''')




df1.to_sql( 'автор2' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор2
         ''')



df2.to_sql( 'автор3' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор3
         ''')



df3.to_sql( 'автор4' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор4
         ''')


df4.to_sql( 'автор5' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор5
         ''')


df5.to_sql( 'автор6' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор6
         ''')


df6.to_sql( 'автор7' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор7
         ''')


df7.to_sql( 'автор8' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор8
         ''')


df8.to_sql( 'автор9' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор9
         ''')


df9.to_sql( 'автор10' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор10
         ''')



df10.to_sql( 'автор11' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор11
         ''')


df11.to_sql( 'автор12' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор12
         ''')


df12.to_sql( 'автор13' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор13
         ''')


df13.to_sql( 'автор14' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор14
         ''')


df14.to_sql( 'автор15' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор15
         ''')


df15.to_sql( 'автор16' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор16
         ''')


df16.to_sql( 'автор17' , conn, if_exists='replace', index = False)
c = conn.cursor()
c.execute('''  SELECT * FROM автор17
         ''')


conn.commit()